[package]
name = "whitesmith"
version = "0.1.0"
authors = ["rloic <loic.rouquette@insa-lyon.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
humantime = "2.1.0"
humantime-serde = "1.0.1"
wait-timeout = "0.2.0"
clap = "2.33.3"
colored = "2.0.0"
ron="0.6.4"
serde = "1.0.125"
rev_lines = "0.2.1"